name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: windows-latest
          - java: 8
            os: ubuntu-latest
          - java: 11
            os: ubuntu-latest
    steps:
    - run: "git config --global core.autocrlf false"
      shell: bash
    - uses: actions/checkout@v4
    - uses: sbt/setup-sbt@v1
    - uses: actions/setup-java@v4
      with:
        java-version: "${{ matrix.java }}"
        distribution: temurin
    - uses: coursier/cache-action@v6
    - shell: bash
      run: sbt
           -v
           scalafmtSbtCheck
           "+scalafmtCheckAll"
           "+compile"
           "+test"
